cmake_minimum_required(VERSION 3.13)
project(rq5_negative_depth LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(OpenFHE 1.4.2 EXACT REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenFHE_CXX_FLAGS}")
include_directories(${OPENMP_INCLUDES} ${OpenFHE_INCLUDE} ${OpenFHE_INCLUDE}/third-party/include ${OpenFHE_INCLUDE}/core ${OpenFHE_INCLUDE}/pke ${OpenFHE_INCLUDE}/binfhe)
link_directories(${OpenFHE_LIBDIR} ${OPENMP_LIBRARIES})
add_executable(negative_depth negative_depth.cpp)
target_link_libraries(negative_depth ${OpenFHE_SHARED_LIBRARIES})
